# This workflow is intended to be used by JB-compose team in https://github.com/JetBrains/androidx
# which is a fork of androidx repo.
# By having this file in the AndroidX upstream we (JB-compose team) avoid the need to
# rebase/cherry-pick the workflow file for every CL we want to submit upstream.

# The aim of this workflow is to run checks and some tests before submitting the CL upstream.
name: JB-COMPOSE-variant of AndroidX Presubmits
on:
  push:
    branches:
      - jb_cl*
      - jb_presubmit*

  pull_request:
    branches:
      - jb-main
      - jb_presubmit*
      - jb_cl*
    types:
      - opened
      - reopened
      - synchronize

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Setup JDK 11"
        id: setup-java
        uses: actions/setup-java@v1
        with:
          java-version: "11"

      - name: "Set environment variables"
        shell: bash
        run: |
          set -x
          echo "ANDROID_SDK_ROOT=$HOME/Library/Android/sdk" >> $GITHUB_ENV
          echo "DIST_DIR=$HOME/dist" >> $GITHUB_ENV

      - run: compose-jb/compose/scripts/downloadAndroidSdk

      - uses: actions/checkout@v3
        with:
          repository: 'JetBrains/compose-jb'
          submodules: 'recursive'
          path: 'compose-jb'

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: compose:ui:desktopTest
          gradle-version: release-candidate
          build-root-directory: compose-jb/compose/frameworks/support
